### ISSUE TITLE
關於新增題目的問題

### ISSUE THREAD

**Issue by Hsuan0223x** [TIOJ-INFOR-Online-Judge/tioj#35]
開發團隊好，我利用了你們提供的code進行下載後
在ubuntu 22.04 server版上
遇到了無法新增題目的問題
以下是我遇到問題以後顯示的log

actionpack (7.0.8.1) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
railties (7.0.8.1) lib/rails/engine.rb:530:in `call'
passenger (6.0.20) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
passenger (6.0.20) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
passenger (6.0.20) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (6.0.20) src/ruby_supportlib/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
passenger (6.0.20) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
I, [2024-08-02T04:25:47.831191 #1877]  INFO -- : Processing by ErrorsController#internal_server_error as HTML
I, [2024-08-02T04:25:47.831251 #1877]  INFO -- :   Parameters: {"authenticity_token"=>"[FILTERED]", "problem"=>{"specjudge_compiler_id"=>"2", "summary_compiler_id"=>"2", "name"=>"uwu ", "description"=>"uwu", "source"=>"uwu", "input"=>"uwu", "output"=>"uwu", "hint"=>"uwu", "visible_state"=>"public", "sjcode"=>"", "interlib"=>"", "specjudge_type"=>"none", "interlib_type"=>"none", "discussion_visibility"=>"disabled", "interlib_impl"=>"", "score_precision"=>"2", "verdict_ignore_td_list"=>"[]", "num_stages"=>"1", "judge_between_stages"=>"0", "default_scoring_args"=>"", "strict_mode"=>"0", "skip_group"=>"1", "ranklist_display_score"=>"0", "code_length_limit"=>"5000000", "specjudge_compile_args"=>"", "summary_type"=>"none", "summary_code"=>""}, "commit"=>"Create Problem"}
I, [2024-08-02T04:25:47.832738 #1877]  INFO -- :   Rendered errors/internal_server_error.html.erb within layouts/application (Duration: 0.1ms | Allocations: 33)
I, [2024-08-02T04:25:47.835309 #1877]  INFO -- :   Rendered layouts/base.erb (Duration: 0.6ms | Allocations: 330)
I, [2024-08-02T04:25:47.835397 #1877]  INFO -- :   Rendered layout layouts/application.html.erb (Duration: 2.7ms | Allocations: 1094)
I, [2024-08-02T04:25:47.835528 #1877]  INFO -- : Completed 500 Internal Server Error in 4ms (Views: 2.6ms | ActiveRecord: 0.9ms | Allocations: 1482)
I, [2024-08-02T04:25:47.884515 #1877]  INFO -- : Started GET "/mathjax/tex-svg-full.js" for 61.218.108.221 at 2024-08-02 04:25:47 +0000
I, [2024-08-02T04:25:47.885965 #1877]  INFO -- : Processing by Mathjax::Rails::MathjaxRailsController#giveOutStaticFile as JS
I, [2024-08-02T04:25:47.886028 #1877]  INFO -- :   Parameters: {"uri"=>"tex-svg-full"}
I, [2024-08-02T04:25:47.886293 #1877]  INFO -- : Sent file /usr/share/rvm/gems/ruby-3.1.2/gems/mathjax-rails-3-3.2.2.3/vendor/mathjax/es5/tex-svg-full.js (0.1ms)
I, [2024-08-02T04:25:47.886358 #1877]  INFO -- : Completed 200 OK in 0ms (ActiveRecord: 0.0ms | Allocations: 132)

**Comment by Hsuan0223x** [comment]
1
